alter table bracket drop foreign key FK830ACA82D3D3981;
alter table bracket drop foreign key FK830ACA851A84409;
alter table champion drop foreign key FK555704698413347A;
alter table champion drop foreign key FK555704691A77F0BA;
alter table champion drop foreign key FK55570469DF904490;
alter table course_city drop foreign key FKFB054B0F5048CBE;
alter table course_city drop foreign key FKFB054B0F491A33BE;
alter table golf_match drop foreign key FK223D6BA85CE8951A;
alter table golf_match drop foreign key FK223D6BA85FFFA8A9;
alter table golf_match drop foreign key FK223D6BA8A10975AC;
alter table golf_match drop foreign key FK223D6BA8B6ABEBC3;
alter table golf_match drop foreign key FK223D6BA8267F3F32;
alter table golf_match drop foreign key FK223D6BA8267F3F31;
alter table match_category drop foreign key FKE2424238491A33BE;
alter table private_message drop foreign key FKA4CB994BE451C3E4;
alter table private_message drop foreign key FKA4CB994BEA1D939E;
alter table public_message drop foreign key FKE377E0311A77F0BA;
alter table public_message drop foreign key FKE377E031DFC2A6FC;
alter table regentry drop foreign key FKD6A18C5E118C97BE;
alter table regentry drop foreign key FKD6A18C5E89ED24FE;
alter table registration drop foreign key FKAF83E8B9491A33BE;
alter table season drop foreign key FKC9FA6AE3491A33BE;
alter table season_match drop foreign key FKCB73B169411D5E36;
alter table season_match drop foreign key FKCB73B16934BB37BE;
alter table ticker drop foreign key FKCBE86B0A491A33BE;
alter table user drop foreign key FK36EBCB8413347A;
alter table user drop foreign key FK36EBCB8A88BDF1;
alter table user drop foreign key FK36EBCBCBD76F19;
alter table user drop foreign key FK36EBCB71CB8030;
alter table user drop foreign key FK36EBCB3D404C57;
alter table user_role drop foreign key FK143BF46A6C61D3DE;
alter table user_role drop foreign key FK143BF46A118C97BE;
drop table if exists bracket;
drop table if exists champion;
drop table if exists city;
drop table if exists course;
drop table if exists course_city;
drop table if exists golf_match;
drop table if exists match_category;
drop table if exists private_message;
drop table if exists public_message;
drop table if exists regentry;
drop table if exists registration;
drop table if exists role;
drop table if exists season;
drop table if exists season_match;
drop table if exists ticker;
drop table if exists user;
drop table if exists user_role;
create table bracket (id bigint not null auto_increment, version integer not null, season_id bigint, match_number integer not null, golf_match bigint not null unique, next bigint, round integer, primary key (id)) ENGINE=InnoDB;
create table champion (id bigint not null auto_increment, version integer not null, player bigint, city bigint, year integer not null, season varchar(255), division varchar(255), record varchar(255) not null, home_course bigint not null, primary key (id)) ENGINE=InnoDB;
create table city (id bigint not null auto_increment, version integer not null, name varchar(255), state varchar(255), active bit, inactive_msg varchar(255), countdown_date datetime, countdown_msg varchar(255), primary key (id)) ENGINE=InnoDB;
create table course (id bigint not null auto_increment, version integer not null, name varchar(255), mens_tee_name varchar(255), mens_pars tinyblob, mens_handicaps tinyblob, mens_yardages blob, womens_tee_name varchar(255), womens_pars tinyblob, womens_handicaps tinyblob, womens_yardages blob, pro_shop_phone varchar(255), tee_time_phone varchar(255), web_site varchar(255), mens_slope integer not null, mens_rating float not null, womens_slope integer not null, womens_rating float not null, primary key (id)) ENGINE=InnoDB;
create table course_city (course_id bigint not null, city_id bigint not null, idx integer not null, primary key (course_id, idx)) ENGINE=InnoDB;
create table golf_match (id bigint not null auto_increment, version integer not null, golfer1 bigint, golfer2 bigint, puttoff_winner bigint, default_winner bigint, round integer not null, play_by datetime not null, played datetime, course bigint, golfer1handicap integer, golfer2handicap integer, p1h1par tinyint, p1h2par tinyint, p1h3par tinyint, p1h4par tinyint, p1h5par tinyint, p1h6par tinyint, p1h7par tinyint, p1h8par tinyint, p1h9par tinyint, p1h10par tinyint, p1h11par tinyint, p1h12par tinyint, p1h13par tinyint, p1h14par tinyint, p1h15par tinyint, p1h16par tinyint, p1h17par tinyint, p1h18par tinyint, p1h1stroke tinyint, p1h2stroke tinyint, p1h3stroke tinyint, p1h4stroke tinyint, p1h5stroke tinyint, p1h6stroke tinyint, p1h7stroke tinyint, p1h8stroke tinyint, p1h9stroke tinyint, p1h10stroke tinyint, p1h11stroke tinyint, p1h12stroke tinyint, p1h13stroke tinyint, p1h14stroke tinyint, p1h15stroke tinyint, p1h16stroke tinyint, p1h17stroke tinyint, p1h18stroke tinyint, p1h1score tinyint, p1h2score tinyint, p1h3score tinyint, p1h4score tinyint, p1h5score tinyint, p1h6score tinyint, p1h7score tinyint, p1h8score tinyint, p1h9score tinyint, p1h10score tinyint, p1h11score tinyint, p1h12score tinyint, p1h13score tinyint, p1h14score tinyint, p1h15score tinyint, p1h16score tinyint, p1h17score tinyint, p1h18score tinyint, p2h1par tinyint, p2h2par tinyint, p2h3par tinyint, p2h4par tinyint, p2h5par tinyint, p2h6par tinyint, p2h7par tinyint, p2h8par tinyint, p2h9par tinyint, p2h10par tinyint, p2h11par tinyint, p2h12par tinyint, p2h13par tinyint, p2h14par tinyint, p2h15par tinyint, p2h16par tinyint, p2h17par tinyint, p2h18par tinyint, p2h1stroke tinyint, p2h2stroke tinyint, p2h3stroke tinyint, p2h4stroke tinyint, p2h5stroke tinyint, p2h6stroke tinyint, p2h7stroke tinyint, p2h8stroke tinyint, p2h9stroke tinyint, p2h10stroke tinyint, p2h11stroke tinyint, p2h12stroke tinyint, p2h13stroke tinyint, p2h14stroke tinyint, p2h15stroke tinyint, p2h16stroke tinyint, p2h17stroke tinyint, p2h18stroke tinyint, p2h1score tinyint, p2h2score tinyint, p2h3score tinyint, p2h4score tinyint, p2h5score tinyint, p2h6score tinyint, p2h7score tinyint, p2h8score tinyint, p2h9score tinyint, p2h10score tinyint, p2h11score tinyint, p2h12score tinyint, p2h13score tinyint, p2h14score tinyint, p2h15score tinyint, p2h16score tinyint, p2h17score tinyint, p2h18score tinyint, stroke1 tinyint, stroke2 tinyint, stroke3 tinyint, stroke4 tinyint, stroke5 tinyint, stroke6 tinyint, stroke7 tinyint, stroke8 tinyint, stroke9 tinyint, stroke10 tinyint, stroke11 tinyint, stroke12 tinyint, stroke13 tinyint, stroke14 tinyint, stroke15 tinyint, stroke16 tinyint, stroke17 tinyint, stroke18 tinyint, score1 tinyint, score2 tinyint, score3 tinyint, score4 tinyint, score5 tinyint, score6 tinyint, score7 tinyint, score8 tinyint, score9 tinyint, score10 tinyint, score11 tinyint, score12 tinyint, score13 tinyint, score14 tinyint, score15 tinyint, score16 tinyint, score17 tinyint, score18 tinyint, p1birdies integer, p1eagles integer, p1dbleagles integer, p1netbirdies integer, p1neteagles integer, p1netdbleagles integer, p2birdies integer, p2eagles integer, p2dbleagles integer, p2netbirdies integer, p2neteagles integer, p2netdbleagles integer, bracket_entry bigint unique, primary key (id)) ENGINE=InnoDB;
create table match_category (id bigint not null auto_increment, version integer not null, city_id bigint not null, name varchar(255), primary key (id)) ENGINE=InnoDB;
create table private_message (id bigint not null auto_increment, version integer not null, receiver bigint not null, sender bigint not null, subject varchar(60) not null, message varchar(1000) not null, sent datetime not null, read_date datetime, primary key (id)) ENGINE=InnoDB;
create table public_message (id bigint not null auto_increment, version integer not null, poster bigint not null, subject varchar(60) not null, message varchar(1000) not null, date datetime not null, city bigint, primary key (id)) ENGINE=InnoDB;
create table regentry (id bigint not null auto_increment, version integer not null, registration_id bigint not null, user_id bigint not null, promo_code varchar(255), response_code varchar(255), response_code_text varchar(255), transaction_id varchar(255), approval_code varchar(255), md5_hash_server varchar(255), primary key (id)) ENGINE=InnoDB;
create table registration (id bigint not null auto_increment, version integer not null, name varchar(255) not null unique, city_id bigint not null, early_start datetime, start datetime not null, end datetime not null, state integer not null, early_registration_fee float, regular_registration_fee float, primary key (id)) ENGINE=InnoDB;
create table role (id bigint not null auto_increment, name varchar(20), description varchar(64), primary key (id)) ENGINE=InnoDB;
create table season (id bigint not null auto_increment, version integer not null, city_id bigint not null, name varchar(255), division varchar(255), qualifiers integer not null, registration_id bigint not null, state integer not null, primary key (id)) ENGINE=InnoDB;
create table season_match (season_id bigint not null, match_id bigint not null, primary key (season_id, match_id)) ENGINE=InnoDB;
create table ticker (id bigint not null auto_increment, version integer not null, city_id bigint not null, message varchar(255), primary key (id)) ENGINE=InnoDB;
create table user (id bigint not null auto_increment, version integer not null, username varchar(50) not null unique, password varchar(255) not null, first_name varchar(50) not null, last_name varchar(50) not null, male bit, address varchar(150) not null, city varchar(50) not null, province varchar(100), country varchar(100), postal_code varchar(15) not null, email varchar(255) not null unique, home_phone varchar(255), cell_phone varchar(255), preferred_phone integer, password_hint varchar(255), registered_city bigint not null, home_course bigint not null, referral varchar(255) not null, icon varchar(255) not null, first_season bigint, date_joined datetime not null, last_login datetime, account_enabled char(1), account_expired char(1) not null, account_locked char(1) not null, credentials_expired char(1) not null, current_season bigint, current_wins integer not null, current_losses integer not null, current_ties integer not null, total_wins integer not null, total_losses integer not null, total_ties integer not null, best_result integer not null, best_result_season bigint, low_score integer, seasons_entered integer not null, player_level double precision not null, ratedby varchar(255) not null, homecourt varchar(255) not null, plays varchar(255) not null, playing_preference tinyblob not null, opentochallenges bit not null, playwithonlysamegender bit not null, opponent_skilllevel tinyblob not null, racket varchar(255) not null, tennisstring varchar(255) not null, shoes varchar(255) not null, primary key (id)) ENGINE=InnoDB;
create table user_role (user_id bigint not null, role_id bigint not null, primary key (user_id, role_id)) ENGINE=InnoDB;
alter table bracket add index FK830ACA82D3D3981 (next), add constraint FK830ACA82D3D3981 foreign key (next) references bracket (id);
alter table bracket add index FK830ACA851A84409 (golf_match), add constraint FK830ACA851A84409 foreign key (golf_match) references golf_match (id);
alter table champion add index FK555704698413347A (home_course), add constraint FK555704698413347A foreign key (home_course) references course (id);
alter table champion add index FK555704691A77F0BA (city), add constraint FK555704691A77F0BA foreign key (city) references city (id);
alter table champion add index FK55570469DF904490 (player), add constraint FK55570469DF904490 foreign key (player) references user (id);
alter table course_city add index FKFB054B0F5048CBE (course_id), add constraint FKFB054B0F5048CBE foreign key (course_id) references course (id);
alter table course_city add index FKFB054B0F491A33BE (city_id), add constraint FKFB054B0F491A33BE foreign key (city_id) references city (id);
alter table golf_match add index FK223D6BA85CE8951A (course), add constraint FK223D6BA85CE8951A foreign key (course) references course (id);
alter table golf_match add index FK223D6BA85FFFA8A9 (bracket_entry), add constraint FK223D6BA85FFFA8A9 foreign key (bracket_entry) references bracket (id);
alter table golf_match add index FK223D6BA8A10975AC (default_winner), add constraint FK223D6BA8A10975AC foreign key (default_winner) references user (id);
alter table golf_match add index FK223D6BA8B6ABEBC3 (puttoff_winner), add constraint FK223D6BA8B6ABEBC3 foreign key (puttoff_winner) references user (id);
alter table golf_match add index FK223D6BA8267F3F32 (golfer2), add constraint FK223D6BA8267F3F32 foreign key (golfer2) references user (id);
alter table golf_match add index FK223D6BA8267F3F31 (golfer1), add constraint FK223D6BA8267F3F31 foreign key (golfer1) references user (id);
alter table match_category add index FKE2424238491A33BE (city_id), add constraint FKE2424238491A33BE foreign key (city_id) references city (id);
alter table private_message add index FKA4CB994BE451C3E4 (sender), add constraint FKA4CB994BE451C3E4 foreign key (sender) references user (id);
alter table private_message add index FKA4CB994BEA1D939E (receiver), add constraint FKA4CB994BEA1D939E foreign key (receiver) references user (id);
alter table public_message add index FKE377E0311A77F0BA (city), add constraint FKE377E0311A77F0BA foreign key (city) references city (id);
alter table public_message add index FKE377E031DFC2A6FC (poster), add constraint FKE377E031DFC2A6FC foreign key (poster) references user (id);
alter table regentry add index FKD6A18C5E118C97BE (user_id), add constraint FKD6A18C5E118C97BE foreign key (user_id) references user (id);
alter table regentry add index FKD6A18C5E89ED24FE (registration_id), add constraint FKD6A18C5E89ED24FE foreign key (registration_id) references registration (id);
alter table registration add index FKAF83E8B9491A33BE (city_id), add constraint FKAF83E8B9491A33BE foreign key (city_id) references city (id);
alter table season add index FKC9FA6AE3491A33BE (city_id), add constraint FKC9FA6AE3491A33BE foreign key (city_id) references city (id);
alter table season_match add index FKCB73B169411D5E36 (match_id), add constraint FKCB73B169411D5E36 foreign key (match_id) references golf_match (id);
alter table season_match add index FKCB73B16934BB37BE (season_id), add constraint FKCB73B16934BB37BE foreign key (season_id) references season (id);
alter table ticker add index FKCBE86B0A491A33BE (city_id), add constraint FKCBE86B0A491A33BE foreign key (city_id) references city (id);
alter table user add index FK36EBCB8413347A (home_course), add constraint FK36EBCB8413347A foreign key (home_course) references course (id);
alter table user add index FK36EBCB8A88BDF1 (best_result_season), add constraint FK36EBCB8A88BDF1 foreign key (best_result_season) references season (id);
alter table user add index FK36EBCBCBD76F19 (first_season), add constraint FK36EBCBCBD76F19 foreign key (first_season) references season (id);
alter table user add index FK36EBCB71CB8030 (current_season), add constraint FK36EBCB71CB8030 foreign key (current_season) references season (id);
alter table user add index FK36EBCB3D404C57 (registered_city), add constraint FK36EBCB3D404C57 foreign key (registered_city) references city (id);
alter table user_role add index FK143BF46A6C61D3DE (role_id), add constraint FK143BF46A6C61D3DE foreign key (role_id) references role (id);
alter table user_role add index FK143BF46A118C97BE (user_id), add constraint FK143BF46A118C97BE foreign key (user_id) references user (id);
